pref("extensions.TweetContext@loucypher.description", "chrome://tweetcontext/locale/tweetcontext.properties");
pref("extensions.TweetContext.enableEchofon", false);
pref("extensions.TweetContext.enableHootBar", false);
pref("extensions.TweetContext.useAddon", 0);
pref("extensions.TweetContext.https", false);
pref("extensions.TweetContext.intro", false);
pref("extensions.TweetContext.openInTab", false);
pref("extensions.TweetContext.useEchofon", false);
pref("extensions.TweetContext.useHootBar", false);
