pref("extensions.ShortenURL@loucypher.description", "chrome://shortenurl/locale/shortenurl.properties");
pref("extensions.shortenURL.autocopy", false);
pref("extensions.shortenURL.autotweet", false);
pref("extensions.shortenURL.baseURL", 0);
pref("extensions.shortenURL.name.0", "TinyURL");
pref("extensions.shortenURL.name.1", "bit.ly");
pref("extensions.shortenURL.name.2", "is.gd");
pref("extensions.shortenURL.name.3", "Metamark (xrl.us)");
pref("extensions.shortenURL.name.4", "SnipURL (sn.im)");
pref("extensions.shortenURL.name.5", "xrl.in");
pref("extensions.shortenURL.name.6", "a.gd");
pref("extensions.shortenURL.name.7", "PiURL");
pref("extensions.shortenURL.name.8", "tr.im");
pref("extensions.shortenURL.name.9", "kl.am");
pref("extensions.shortenURL.name.10", "cli.gs");
pref("extensions.shortenURL.name.11", "urlBorg");
pref("extensions.shortenURL.name.12", "Moourl");
pref("extensions.shortenURL.name.13", "Plurl");
pref("extensions.shortenURL.name.14", "Pendek.in");
pref("extensions.shortenURL.name.15", "Chilp.it");
pref("extensions.shortenURL.name.16", "Kurze (krz.ch)");
pref("extensions.shortenURL.name.17", "urlzen");
pref("extensions.shortenURL.name.18", "Smallr.net");
pref("extensions.shortenURL.name.19", "Twirl.at");
pref("extensions.shortenURL.name.20", "Tweetburner (twurl.nl)");
pref("extensions.shortenURL.name.21", "idek.net");
pref("extensions.shortenURL.name.22", "urlShort (u.mavrev.com)");
pref("extensions.shortenURL.name.23", "hex.io");
pref("extensions.shortenURL.name.24", "Short.ie");
pref("extensions.shortenURL.name.25", "BurnURL");
pref("extensions.shortenURL.name.26", "DiggBar");
pref("extensions.shortenURL.name.27", "ZipMyURL");
pref("extensions.shortenURL.name.28", "abbr");
pref("extensions.shortenURL.name.29", "Lincr");
pref("extensions.shortenURL.0", "http://tinyurl.com/api-create.php?url=");
pref("extensions.shortenURL.1", "http://bit.ly/api?url=");
pref("extensions.shortenURL.2", "http://is.gd/api.php?longurl=");
pref("extensions.shortenURL.3", "http://metamark.net/api/rest/simple?long_url=");
pref("extensions.shortenURL.4", "http://sn.im/site/snip?r=simple&link=");
pref("extensions.shortenURL.5", "http://xrl.in/?r=key&xrl=");
pref("extensions.shortenURL.6", "http://a.gd/?module=ShortURL&file=Add&mode=API&url=");
pref("extensions.shortenURL.7", "http://piurl.com/api.php?url=");
pref("extensions.shortenURL.8", "http://tr.im/api/trim_url.json?url=");
pref("extensions.shortenURL.9", "http://kl.am/api/shorten?format=text&url=");
pref("extensions.shortenURL.10", "http://cli.gs/api/v1/cligs/create?url=");
pref("extensions.shortenURL.11", "http://urlborg.com/api/163129-9725/create_or_reuse/");
pref("extensions.shortenURL.12", "http://pipes.yahoo.com/pipes/pipe.run?_id=7bb411cbb7bd34aa30900dd089c19e8f&_render=json&url=");
pref("extensions.shortenURL.13", "http://pipes.yahoo.com/pipes/pipe.run?_id=89935aab880ff4a92e5b05917da149b5&_render=json&url=");
pref("extensions.shortenURL.14", "http://pendek.in/?url=");
pref("extensions.shortenURL.15", "http://chilp.it/api.php?url=");
pref("extensions.shortenURL.16", "http://krz.ch/?module=ShortURL&file=Add&mode=API&url=");
pref("extensions.shortenURL.17", "http://urlzen.com/api?url=");
pref("extensions.shortenURL.18", "http://smallr.net/api?url=");
pref("extensions.shortenURL.19", "http://twirl.at/api.php?url=");
pref("extensions.shortenURL.20", "http://pipes.yahoo.com/pipes/pipe.run?_id=f7dfd7156e3b2e0071f0fb6293becb56&_render=json&urlinput=");
pref("extensions.shortenURL.21", "http://idek.net/c.php?idek-api=true&idek-ref=firefox_shorten_url_extension&idek-url=");
pref("extensions.shortenURL.22", "http://u.mavrev.com/api.php?url=");
pref("extensions.shortenURL.23", "http://hex.io/api-create.php?url=");
pref("extensions.shortenURL.24", "http://short.ie/api?format=plain&url=");
pref("extensions.shortenURL.25", "http://burnurl.com/?output=plain&url=");
pref("extensions.shortenURL.26", "http://services.digg.com/url/short/create?appkey=http%3A%2F%2Floucypher.mp%2F&type=json&url=");
pref("extensions.shortenURL.27", "http://zipmyurl.com/api.do?api=true&url=");
pref("extensions.shortenURL.28", "http://api.abbrr.com/api.php?out=link&url=");
pref("extensions.shortenURL.29", "http://lin.cr/?mode=api&l=");

